### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by danwissa**
Added release keys for .NET 4.6.2 Preview
Fix Get.NET link on main page issue: https://github.com/shanselman/SmallestDotNet/issues/60

### CODE REVIEW

**Comment by shanselman** [comment]
Cool! I found a link of those 6 digit numbers here https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx so maybe we can get a complete list and be totally up to date.

**Comment by danwissa** [comment]
At a quick glance when I got the 4.6.2 preview keys it looked like the other keys in that link are already there.

I would be happy to take up an activity to cross reference all of them against the code and double check that we are up to date. How does that sound?

Also, any other things I can help with on this project?



On Thu, Apr 7, 2016 at 1:35 PM -0700, "Scott Hanselman" <notifications@github.com<mailto:notifications@github.com>> wrote:


Cool! I found a link of those 6 digit numbers here https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx so maybe we can get a complete list and be totally up to date.

-

**Comment by danwissa** [comment]
Just did a cross reference between what we have and the MSDN link, we are totally up to date for everything 4.5 and above. We also have 3 redundant keys now for .NET 4.6 Preview, RC1 & RC2 which no longer show on the site, I guess doesn't hurt to keep them.

Also found that on the latest RedStone build 14316 which I'm currently running, it is using release key _394757_ which is currently not in the MSDN link still!

I can add that into the list and submit a new PR, sound good?

**Comment by shanselman** [comment]
Sure

**Comment by danwissa** [comment]
Hi Scott, thanks for that. Now done: https://github.com/shanselman/SmallestDotNet/pull/74

**Pull request merged**
