### PR TITLE
Update to include versions upto 4.7.2

### PR DESCRIPTION
**Pull request by grhm**
Added the release key numbers for 4.7, 4.7.1 and 4.7.2
Altered the main web page to mention 4.7 and to default to downloading v4.7.2

### CODE REVIEW

**Comment by shanselman** [comment]
Sorry, didn't see this in my inbox if 1934 notifications. ;)

**Comment by shanselman** [comment]
Closes #83, #86, #88, #89, #90, #91, #94, #95, #97, #98, #99.

**Comment by dpisanu** [comment]
I see a podcast episode in there:
'the downside of public repos. owners swamped by PRs' :p

**Comment by grhm** [comment]
@dpisanu There's already a blog post 😉😃  https://www.hanselman.com/blog/AlwaysBeClosingPullRequests.aspx 
@shanselman Might be worth looikng into something like [OctoBox](https://github.com/octobox/octobox) to help with the notifications.

**Pull request merged**
